
server.port=8082

custom.message=Question Service Config

#Resilience4j circuit breaker config
management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.questionService.register-health-indicator=true
resilience4j.circuitbreaker.instances.questionService.sliding-window-size=5
resilience4j.circuitbreaker.instances.questionService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.questionService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.questionService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.questionService.automatic-transition-from-open-to-half-open-enabled=true

management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
