server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/micro_services_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql@2003

# JPA
spring.jpa.hibernate.ddl-auto=update

# Test Property
custom.message=Hello From Config Server
